// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3hz8x1EIsu30bYDioKwCyyclmyH1DOfY',
    appId: '1:730737173539:web:388ab992e55f7d3870bd96',
    messagingSenderId: '730737173539',
    projectId: 'paw-chat-ca340',
    authDomain: 'paw-chat-ca340.firebaseapp.com',
    storageBucket: 'paw-chat-ca340.appspot.com',
    measurementId: 'G-17P001JLN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFtvf2EuU2n7g9QchYHuZIE0LnwMIqA7Q',
    appId: '1:730737173539:android:6ed1893cda57812970bd96',
    messagingSenderId: '730737173539',
    projectId: 'paw-chat-ca340',
    storageBucket: 'paw-chat-ca340.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlPoYD9P3_ZPDJ2GfVBwsFZBbEtRCy_3U',
    appId: '1:730737173539:ios:e225408c3d9c73e870bd96',
    messagingSenderId: '730737173539',
    projectId: 'paw-chat-ca340',
    storageBucket: 'paw-chat-ca340.appspot.com',
    iosClientId: '730737173539-ti7uvglqr0u1ih0a7mu05glcsqbsunqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlPoYD9P3_ZPDJ2GfVBwsFZBbEtRCy_3U',
    appId: '1:730737173539:ios:f4da3e0c5f4d41ea70bd96',
    messagingSenderId: '730737173539',
    projectId: 'paw-chat-ca340',
    storageBucket: 'paw-chat-ca340.appspot.com',
    iosClientId: '730737173539-7tm4t6bpno5j6e37ek0hjkfosu5n5qvq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp.RunnerTests',
  );
}
